# Generated by Django 4.2.5 on 2023-10-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_transaction_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='balance',
        ),
    ]
