# Generated by Django 4.2.5 on 2023-10-21 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_bankaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account_new',
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='FiscalYear',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='transactions',
        ),
        migrations.DeleteModel(
            name='Transaction_new',
        ),
        migrations.RemoveField(
            model_name='transactionentry',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transactionentry',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.category'),
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='TransactionEntry',
        ),
    ]
